config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/admin/users_count', to: 'admin#users_count'
  get 'users', to: 'all_users#index'
  resources :items do
    get :upvote, on: :member
    get :expensive, on: :collection
  end
  root to: 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_many :comments, as: :commentable
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  # has_and_belongs_to_many :items
  has_many :positions
  has_many :items, through: :positions
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :price, numericality: { greater_than: 0 }
  validates :name, presence: true
  has_many :positions
  has_many :carts, through: :positions
  has_many :comments, as: :commentable
  has_one  :image, as: :imageable
  has_and_belongs_to_many :orders
  after_create { p "create" }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :items
  def calculate_total
    write_attribute :total, items.map(&:price).inject(:+)
  end
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :comments
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :admin?
  # layout 'admin'
  def users_count
    @users_count = User.count
    render layout: 'admin'
  end
end

app/controllers/all_users_controller.rb
class AllUsersController < ApplicationController

  def index
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def render_403
    render file: 'public/403.html', status: :forbidden
  end
  def admin?
     render_403 unless params[:admin]
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: %i[show edit update destroy upvote]
  before_action :admin?, only: %i[edit]
  skip_before_action :verify_authenticity_token
  def index
    @items = Item.all.order(:votes_count).order(:id).includes(:image)
  end

  def new
    @item = Item.new
  end

  def show
    render body: 'Page not found', status: 404 unless @item
  end

  def edit
    render body: 'Page not found', status: 404 unless @item
  end

  def update
    if @item.update(items_params)
      redirect_to item_path
    else
      flash[:error] = 'Please fii all fields correctly'
      render json: item.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @item.destroy
      # redirect_to items_path
      render json: { success: true }
    else
      flash[:error] = 'Item was deleted'
      # render json: item.error, status: :unprocessable_entity
    end
  end

  def create
    @item = Item.create(items_params)
    if @item.persisted?
      flash[:success] = 'All correct'
      redirect_to items_path
    else
      flash.now[:error] = 'Please fii all fields correctly'
      render :new
    end
  end

  def upvote
    @item.increment! :votes_count
    redirect_to items_path
  end

  def expensive
    @items = Item.where('price > 50')
    render :index
  end
  private
  def items_params
    params.require(:item).permit(:name, :price, :description)
  end

  def find_item
    @item = Item.where(id: params[:id]).first
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/all_users_helper.rb
module AllUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def urls_to_images(html)
    html.gsub! ( %r{https://[^\s<]+} ) do |url|
      "<img src='#{url}' width='100'; />"
    end
    html.html_safe
 end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/users_count.html.erb
<div>
  <h3>Count users : <%= @users_count %> on this site</h3>
  <%= render :partial => 'shared/email' %>
</div>

app/views/admin/users_count.html.haml
%div
  %h3
    Count users : #{@users_count} on this site
  = render :partial => 'shared/email'

app/views/all_users/index.html.erb
<table class="table">
<tr>
  <th class="table-info" scope="col">id</th>
  <th class="table-info" scope="col">email</th>
  <th class="table-info" scope="col">created_at</th>
  <th class="table-info" scope="col">updated_at</th>
</tr>
  <% @users.each do |user| %>
    <tr>
      <th class="table-info" scope="col"><%=user.id %></th>
      <th class="table-info" scope="col"><%=user.email %></th>
      <th class="table-info" scope="col"><%=user.created_at %></th>
      <th class="table-info" scope="col"><%=user.updated_at %></th>
    </tr>

  <% end %>
</table>

app/views/all_users/new.html.erb
<%= @users.each do |user| %>
    <li><%=user.login %></li>
<% end %>

app/views/include/_notification.html.erb
<% if notice %>
<p class="notice alert-success"><%= notice %></p>
<% end %>
<% if alert %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/items/edit.html.haml
%h2 Edit item
= form_tag item_path(@item), method: :put do
  = label_tag :name
  = text_field_tag :name , @item.name
  = label_tag :price
  = text_field_tag :price , @item.price
  = label_tag :description
  = text_field_tag :description , @item.description
  = submit_tag 'Save', class: 'btn btn-large'
= render :partial =>  'shared/email'

app/views/items/erb/edit.html.erb
<h2>Edit item</h2>

<%= form_tag item_path(@item), method: :put do%>
  <%= label_tag :name %>
  <%= text_field_tag :name , @item.name %>
  <%= label_tag :price %>
  <%= text_field_tag :price , @item.price %>
  <%= label_tag :description %>
  <%= text_field_tag :description , @item.description %>
  <%= submit_tag 'Save', class: 'btn btn-large'  %>
<% end %>

<%= render :partial =>  'shared/email'%>

app/views/items/erb/index.html.haml
- if @items.empty?
  %h3 No items, add item
  = link_to  'new item' , new_item_path
  %br/
- else
  %h2 All items
  %table.my_table
    %tr
      %th item id
      %th Name
      %th Price
      %th Description
      %th Rating
      %th Image
      %th Delete
    - @items.each do |item|
      %tr
        %th= item.id
        %th= link_to item.name, item_path(item)
        %th= item.price
        %th= item.description
        %th
          = item.votes_count
          = link_to '+', upvote_item_path(item)
        %th= !item.image.nil? ? image_tag(item.image.file, width: '30px', height: '30px'):'no img'
        %th= button_to 'delete', item_path(item), method: :delete, class: 'deleteAction'
  %br/
  = button_to  'new item' , new_item_path, method: :get
  %br/
  = button_to 'item expensive', expensive_items_path, method: :get
  %br/
  = button_to 'index', items_path, method: :get
  %br/
  = button_to 'admin panel', admin_users_count_path, method: :get
  %br/
= render :partial =>  'shared/email'

app/views/items/erb/new.html.erb
<h2>New item</h2>

<%= simple_form_for @item do |f| %>
<%= f.input :name, input_html: {class:"form-text"}, required:true %>
<%= f.input :price,input_html: {class:"form-text"}, required:true %>
<%= f.input :description, label: t("item.description"), input_html: {class:"form-text"}, required:true %>

<%= f.button :submit,  class: 'btn-primary'  %>
<% end %>

<%= render :partial =>  'shared/email'%>

app/views/items/index.html.erb
<% if @items.empty? %>
<h3>No items, add item</h3>
<%=  link_to  'new item' , new_item_path  %> <br/>
<% else %>
  <h2>All items</h2>
<table class="table">
  <tr>
    <th class="table-info" scope="col">item id</th>
    <th class="table-info" scope="col">Name</th>
    <th class="table-info" scope="col">Price</th>
    <th class="table-info" scope="col">Description</th>
    <th class="table-info" scope="col">Rating</th>
    <th class="table-info" scope="col">Image</th>
    <th class="table-info" scope="col">Delete</th>
  </tr>
  <% @items.each do |item| %>
  <tr data-item_id = "<%= item.id %>">
    <th scope="col"><%= item.id  %></th>
    <th scope="col"><%= link_to item.name, item_path(item) %></th>
    <th scope="col"><%=  item.price  %></th>
    <th scope="col"><%=  item.description %></th>
    <th scope="col"><%= item.votes_count %> <%=  link_to '+', upvote_item_path(item)  %></th>
    <th scope="col"><%= !item.image.nil? ? image_tag(item.image.file, width: '30px', height: '30px'):'no img' %></th>
    <th scope="col" class="deleteAction"><button class="btn btn-outline-primary">Delete</button></th>
  </tr>
  <%  end  %>
</table>
  <div class="btn-group" role="group" aria-label="Basic outlined example">
    <%=  button_to  'new item' , new_item_path, method: :get, class:'btn btn-outline-primary'  %> <br/>
    <%=  button_to 'item expensive', expensive_items_path, method: :get, class:'btn btn-outline-primary' %>  <br/>
    <%=  button_to 'index', items_path, method: :get, class:'btn btn-outline-primary'  %> <br/>
    <%=  button_to 'admin panel', admin_users_count_path, method: :get, class:'btn btn-outline-primary'  %> <br/>
  </div>

<%  end %>

<%= render :partial =>  'shared/email'%>

app/views/items/new.html.haml
%h2 New item
= simple_form_for @item do |f|
  = f.input :name, input_html: {class:"form-text"}, required:true
  = f.input :price,input_html: {class:"form-text"}, required:true
  = f.input :description, label: t("item.description"), input_html: {class:"form-text"}, required:true
  = f.button :submit,  class: 'btn-primary'
= render :partial =>  'shared/email'

app/views/items/show.html.haml
%h2{style:"color:red;"}Show item
%br
%h3= @item.name.upcase
%ul
    %li Id:         #{@item.id}
    %li Name        #{@item.name }
    %li Price       #{@item.price}
    %li Description #{urls_to_images(@item.description)}
%br
= button_to "edit #{@item.name}", edit_item_path, method: :get
= button_to "delete #{@item.name}", item_path(@item), method: :delete
= button_to "index", items_path, method: :get
%br
= render :partial =>  'shared/email'

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1 style="color: rebeccapurple; text-align: center">Admin panel</h1>
    <%= yield %>
  <footer>
    <%= link_to "Home", root_path %>
  </footer>
  </body>
</html>

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RailsBlog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %h1{:style => "color: rebeccapurple; text-align: center"} Admin panel
    = yield
    %footer
      = link_to "Home", root_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render :partial => 'shared/navbar' %>
  <h1 style="color: rebeccapurple; text-align: center">User course</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RailsBlog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %h1{:style => "color: rebeccapurple; text-align: center"} User course
    =render :partial =>  'include/notification'
    = yield

app/views/shared/_email.html.erb
<div class="email" style="font-size: 12px">
  <%= mail_to 'zhenia.galanix@gmail.com'  do %>
    <h3 style="color: #B00100">All questions write email</h3>
   <p>test@gmail.com</p>
  <% end %>
</div>

app/views/shared/_email.html.haml
.email{:style => "font-size: 12px"}
  = mail_to 'zhenia.galanix@gmail.com'  do
    %h3{:style => "color: #B00100"} All questions write email
    %p test@gmail.com

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in?%>
          <li class="nav-item"> <a href="#" class="btn btn-sml" style="color: mediumslateblue">
            Welcome, <%= current_user.email %>
          </a></li>
          <li class="nav-item"><%= link_to 'Quit', destroy_user_session_path, method: :delete, class: 'btn btn-dark' %></li>
          <li class="nav-item"><%= link_to 'Change', edit_user_registration_path, class: 'btn btn-dark' %></li>
          <li class="nav-item"><%= link_to 'All users', users_path, class: 'btn btn-dark' %></li>
          <li class="nav-item"><%= link_to 'All items (Home)', root_path, class: 'btn btn-dark' %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'All users', users_path, class: 'btn btn-dark' %></li>
          <li class="nav-item"><%= link_to 'All items (Home)', root_path, class: 'btn btn-dark' %></li>
         <li class="nav-item"><%= link_to 'Enter', new_user_session_path,  class: 'btn btn-dark' %></li>
          <li class="nav-item"><%= link_to 'Registration', new_user_registration_path, class: 'btn btn-dark' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>